substitutions:
  friendly_name: Office Fan

esphome:
  name: office-fan

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Office-Fan Fallback Hotspot"
    password: !secret ap_ssid_password

web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

captive_portal:

# Example configuration entry
i2c:
  sda: GPIO8
  scl: GPIO9

binary_sensor:
  - platform: gpio
    id: "office_fan_rotary_encoder_button"
    pin:
      number: GPIO7
      mode: INPUT_PULLUP
      inverted: True
    on_release:
      then:
        - fan.toggle: office_fan_obj

sensor:
  - platform: aht10
    temperature:
      name: "Office Temperature"
      id: "office_temperature"
    humidity:
      name: "Office Humidity"
      id: "office_humidity"

  - platform: rotary_encoder
    pin_a: GPIO5
    pin_b: GPIO6
    id: "office_fan_rotaty_encoder_sensor"
    on_clockwise:
      then:
        lambda: |-
          auto fan = id(office_fan_obj);
          int newSpeed = fan->speed + 10;
          auto call = fan->turn_on();
          call.set_speed(newSpeed);
          call.perform();

    on_anticlockwise:
      then:
        lambda: |-
          auto fan = id(office_fan_obj);
          int newSpeed = fan->speed - 10;
          auto call = fan->turn_on();
          call.set_speed(newSpeed);
          call.perform();

  - platform: pulse_counter
    update_interval: 1s
    pin: 
      number: GPIO4
      mode: INPUT_PULLUP
    unit_of_measurement: 'RPM'
    id: office_fan_rpm
    name: $friendly_name RPM
    accuracy_decimals: 0
    filters:
      - multiply: 0.5  # Depending on how many pulses the fan sends per round - should be 0.5 or 1 - try...

output:
  - platform: ledc
    id: office_fan_output
    pin: GPIO3
    frequency: "25000 Hz" 
    min_power: 0%
    max_power: 100%

fan:
  - platform: speed
    output: office_fan_output
    restore_mode: ALWAYS_OFF
    name: "Office Fan"
    id: office_fan_obj
